# Generated by Django 5.1.2 on 2024-11-29 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500, verbose_name='Действие')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('is_nice_habit', models.BooleanField(verbose_name='Признак приятной привычки')),
                ('period', models.CharField(choices=[('day', 'Ежедневно'), ('week', 'Еженедельно')], default='day', max_length=4, verbose_name='Периодичность')),
                ('remuneration', models.CharField(blank=True, max_length=500, null=True, verbose_name='Поощрение')),
                ('time_to_done', models.TimeField(verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(verbose_name='Публичная привычка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('linked_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_habits', to='habits.habit', verbose_name='Связанная привычка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_success', models.BooleanField(verbose_name='Выполнено')),
                ('report', models.TextField(blank=True, null=True, verbose_name='Отчет')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='habits.habit', verbose_name='Привычка')),
            ],
            options={
                'verbose_name': 'отчет',
                'verbose_name_plural': 'отчеты',
            },
        ),
    ]
