# Generated by Django 5.1.2 on 2024-11-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_date_time_alter_habit_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='place',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Место'),
        ),
    ]
