# Generated by Django 5.1.2 on 2024-11-29 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_remove_habit_time_to_done_alter_habit_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='time_to_done',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время на выполнение (в секундах)'),
        ),
    ]
