# Generated by Django 5.1.2 on 2024-11-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_habit_time_to_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='next_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата следующей отправки уведомления'),
        ),
    ]
